/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    registerCallback
 * Signature: (LMain/Callback;)I
 */
JNIEXPORT jint JNICALL Java_Main_registerCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Main
 * Method:    callRegisteredCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Main_callRegisteredCallback
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
